In [1]:
# Use this example - https://machinelearningmastery.com/develop-your-first-neural-network-with-pytorch-step-by-step/ to understand pytorch NNs.
# Augment the dataset by perturbing the data fields with gaussian noise. Train/test/validate. Take a screencast walkthrough of the full code,
# including your understanding of how the NN is implemented.

In [2]:
#Importing Dependencies required

import torch
import torch.nn as nn
import pandas as pd
import random
import torch.optim as optim
from sklearn.model_selection import train_test_split

In [3]:
#Loading the Dataset

In [4]:
df = pd.read_csv("pima-indians-diabetes.data.csv" ,names=['Pregnancies', 'Glucose', 'BP', 'Skin thickness', 'Insulin','BMI','Function','Age','Outcome'])

In [5]:
df.head()             #Printing first 5 data alone

Pregnancies  Glucose  BP  Skin thickness  Insulin   BMI  Function  Age  \
0            6      148  72              35        0  33.6     0.627   50   
1            1       85  66              29        0  26.6     0.351   31   
2            8      183  64               0        0  23.3     0.672   32   
3            1       89  66              23       94  28.1     0.167   21   
4            0      137  40              35      168  43.1     2.288   33   

   Outcome  
0        1  
1        0  
2        1  
3        0  
4        1

In [6]:
#Splitting the Dataset into Data and targets

X = df.drop("Outcome", axis = 1).values
Y = df["Outcome"].values

In [7]:
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [8]:
print(Y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

In [9]:
#Converting the data to tensors

X=torch.tensor(X,dtype=torch.float32)
Y=torch.tensor(Y,dtype=torch.float32).reshape(-1,1)

In [10]:
print(X)

tensor([[  6.0000, 148.0000,  72.0000,  ...,  33.6000,   0.6270,  50.0000],
        [  1.0000,  85.0000,  66.0000,  ...,  26.6000,   0.3510,  31.0000],
        [  8.0000, 183.0000,  64.0000,  ...,  23.3000,   0.6720,  32.0000],
        ...,
        [  5.0000, 121.0000,  72.0000,  ...,  26.2000,   0.2450,  30.0000],
        [  1.0000, 126.0000,  60.0000,  ...,  30.1000,   0.3490,  47.0000],
        [  1.0000,  93.0000,  70.0000,  ...,  30.4000,   0.3150,  23.0000]])


In [11]:
#Splitting the data to training and testing data

X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_train, Y_train, test_size=0.25, random_state=0) #further splitting the train data into train set and validation set

In [12]:
print(X_train)

tensor([[  1.0000, 111.0000,  62.0000,  ...,  24.0000,   0.1380,  23.0000],
        [  0.0000, 106.0000,  70.0000,  ...,  39.4000,   0.6050,  22.0000],
        [  0.0000, 101.0000,  76.0000,  ...,  35.7000,   0.1980,  26.0000],
        ...,
        [  4.0000, 134.0000,  72.0000,  ...,  23.8000,   0.2770,  60.0000],
        [  5.0000, 128.0000,  80.0000,  ...,  34.6000,   0.1440,  45.0000],
        [  1.0000,  71.0000,  78.0000,  ...,  33.2000,   0.4220,  21.0000]])


In [13]:
#printing the shape of the training and testing
print(X.shape,X_train.shape, X_test.shape)

torch.Size([768, 8]) torch.Size([460, 8]) torch.Size([154, 8])


In [14]:
#Creating Model with Pytorch

class ANN_Model(nn.Module):
    def __init__(self,input_features,hidden1,hidden2,output):
        super().__init__()
        self.f_connected1=nn.Linear(input_features,hidden1)
        self.act1 = nn.ReLU()
        self.f_connected2=nn.Linear(hidden1,hidden2)
        self.act2 = nn.ReLU()
        self.out=nn.Linear(hidden2,output)
        self.act_output = nn.Sigmoid()

    def forward(self,x):
        x= self.act1(self.f_connected1(x))
        x= self.act2(self.f_connected2(x))
        x= self.act_output(self.out(x))
        return x

In [15]:
#Initializing the Model
model = ANN_Model(8,12,12,1)
print(model)

ANN_Model(
  (f_connected1): Linear(in_features=8, out_features=12, bias=True)
  (act1): ReLU()
  (f_connected2): Linear(in_features=12, out_features=12, bias=True)
  (act2): ReLU()
  (out): Linear(in_features=12, out_features=1, bias=True)
  (act_output): Sigmoid()
)


In [16]:
#Setting up Loss function and optimizers

loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [17]:
#Training the Model

n_epochs = 100
batch_size = 10

for epoch in range(n_epochs):
    model.train()
    train_loss = 0
    for i in range(0, len(X_train), batch_size):
        Xbatch = X_train[i:i+batch_size]
        y_pred = model(Xbatch)
        ybatch = y_train[i:i+batch_size]
        loss = loss_fn(y_pred, ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(X_train) / batch_size
    #Validation Part
    model.eval()
    with torch.no_grad():
        val_loss = 0
        for i in range(0, len(X_val), batch_size):
            Xbatch = X_val[i:i+batch_size]
            ybatch = y_val[i:i+batch_size]
            y_pred=model(Xbatch)
            val_loss += loss_fn(y_pred, ybatch)
        val_loss /= len(X_val) / batch_size
    if epoch % 10 == 0:
      print(f"Epoch: {epoch}, Train Loss: {train_loss:.4f},  Val Loss: {val_loss:.4f}")

Epoch: 0, Train Loss: 1.3224,  Val Loss: 0.6957
Epoch: 10, Train Loss: 0.6127,  Val Loss: 0.6847
Epoch: 20, Train Loss: 0.5871,  Val Loss: 0.6705
Epoch: 30, Train Loss: 0.5698,  Val Loss: 0.6612
Epoch: 40, Train Loss: 0.5561,  Val Loss: 0.6630
Epoch: 50, Train Loss: 0.5391,  Val Loss: 0.6581
Epoch: 60, Train Loss: 0.5417,  Val Loss: 0.6681
Epoch: 70, Train Loss: 0.5289,  Val Loss: 0.6517
Epoch: 80, Train Loss: 0.5254,  Val Loss: 0.6658
Epoch: 90, Train Loss: 0.5193,  Val Loss: 0.6435


In [18]:
#getting the Loss for Test Data

with torch.no_grad():
    y_pred = model(X_test)
    test_loss = loss_fn(y_pred, Y_test)

print(f'Test loss: {test_loss.item()}')

Test loss: 0.5218632817268372


In [19]:
#getting the accuracy of the model

y_pred = model(X_test) #predicting the accuraccy
accuracy = (y_pred.round() == Y_test).float().mean()
print(f"Accuracy {accuracy}")

Accuracy 0.7532467246055603


In [20]:

#Printing the model output for frist 5 data

predictions = (model(X_test) > 0.5).int()
for i in range(5):
    print(f'{y_pred[i].item()} => {predictions[i].item()} (expected {Y_test[i].item()})')

0.6825464367866516 => 1 (expected 1.0)
0.09744943678379059 => 0 (expected 0.0)
0.28870463371276855 => 0 (expected 0.0)
0.537700891494751 => 1 (expected 1.0)
0.28779736161231995 => 0 (expected 0.0)


In [21]:

#Augmenting the dataset by adding noise

def add_noise(data,target,mean=0,std=0.2):
        noise_data = data.clone()
        noise = torch.randn(noise_data.size()) * std + mean
        noise_data += noise
        return torch.cat([data, noise_data],dim=0) , torch.cat([target,target],dim=0)

In [22]:
#Calling the function add noise
aug_data, aug_target = add_noise(X_train,y_train)

In [23]:
print(X_train[:10,:])
X_train.shape

tensor([[1.0000e+00, 1.1100e+02, 6.2000e+01, 1.3000e+01, 1.8200e+02, 2.4000e+01,
         1.3800e-01, 2.3000e+01],
        [0.0000e+00, 1.0600e+02, 7.0000e+01, 3.7000e+01, 1.4800e+02, 3.9400e+01,
         6.0500e-01, 2.2000e+01],
        [0.0000e+00, 1.0100e+02, 7.6000e+01, 0.0000e+00, 0.0000e+00, 3.5700e+01,
         1.9800e-01, 2.6000e+01],
        [6.0000e+00, 8.5000e+01, 7.8000e+01, 0.0000e+00, 0.0000e+00, 3.1200e+01,
         3.8200e-01, 4.2000e+01],
        [5.0000e+00, 1.1200e+02, 6.6000e+01, 0.0000e+00, 0.0000e+00, 3.7800e+01,
         2.6100e-01, 4.1000e+01],
        [1.0000e+00, 9.3000e+01, 5.6000e+01, 1.1000e+01, 0.0000e+00, 2.2500e+01,
         4.1700e-01, 2.2000e+01],
        [1.0000e+00, 8.9000e+01, 7.6000e+01, 3.4000e+01, 3.7000e+01, 3.1200e+01,
         1.9200e-01, 2.3000e+01],
        [3.0000e+00, 1.1600e+02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3500e+01,
         1.8700e-01, 2.3000e+01],
        [7.0000e+00, 1.5000e+02, 7.8000e+01, 2.9000e+01, 1.2600e+02, 3.5200e+01,

torch.Size([460, 8])

In [24]:
print(aug_data)
aug_data.shape

tensor([[ 1.0000e+00,  1.1100e+02,  6.2000e+01,  ...,  2.4000e+01,
          1.3800e-01,  2.3000e+01],
        [ 0.0000e+00,  1.0600e+02,  7.0000e+01,  ...,  3.9400e+01,
          6.0500e-01,  2.2000e+01],
        [ 0.0000e+00,  1.0100e+02,  7.6000e+01,  ...,  3.5700e+01,
          1.9800e-01,  2.6000e+01],
        ...,
        [ 4.2315e+00,  1.3411e+02,  7.1743e+01,  ...,  2.3828e+01,
          1.9098e-01,  5.9921e+01],
        [ 4.8339e+00,  1.2793e+02,  8.0175e+01,  ...,  3.4318e+01,
         -1.1057e-01,  4.5066e+01],
        [ 1.0543e+00,  7.0930e+01,  7.7860e+01,  ...,  3.2910e+01,
          6.2358e-01,  2.1078e+01]])


torch.Size([920, 8])

In [25]:
#printing the augmenting data size
aug_data.shape

torch.Size([920, 8])

In [26]:
#Initializing the augmented model
aug_model = ANN_Model(8,12,12,1)
print(aug_model)

ANN_Model(
  (f_connected1): Linear(in_features=8, out_features=12, bias=True)
  (act1): ReLU()
  (f_connected2): Linear(in_features=12, out_features=12, bias=True)
  (act2): ReLU()
  (out): Linear(in_features=12, out_features=1, bias=True)
  (act_output): Sigmoid()
)


In [27]:
#Setting up Loss function and optimizers

loss_fn_aug = nn.BCELoss()
aug_optimizer = optim.Adam(aug_model.parameters(), lr=0.01)

In [28]:
#Training the model after augmenting

n_epochs = 150
batch_size = 15
for epoch in range(n_epochs):
    model.train()
    train_loss = 0
    for i in range(0, len(aug_data), batch_size):
        Xbatch = aug_data[i:i+batch_size]
        y_pred = aug_model(Xbatch)
        ybatch = aug_target[i:i+batch_size]
        loss = loss_fn_aug(y_pred, ybatch)
        aug_optimizer.zero_grad()
        loss.backward()
        aug_optimizer.step()
        train_loss += loss.item()
    train_loss /=len(aug_data)/batch_size
    model.eval()
    with torch.no_grad():
        val_loss=0
        val_losses=[]
        for i in range(0, len(X_val), batch_size):
            Xbatch = X_val[i:i+batch_size]
            ybatch = y_val[i:i+batch_size]
            y_pred=aug_model(Xbatch)
            val_loss += loss_fn_aug(y_pred, ybatch)
        val_loss /=len(X_val)/batch_size

    if epoch % 10 == 0:

      print(f"Epoch: {epoch}, Train Loss: {train_loss:.4f},  Val Loss: {val_loss:.4f}")

Epoch: 0, Train Loss: 0.7196,  Val Loss: 0.7061
Epoch: 10, Train Loss: 0.5711,  Val Loss: 0.5912
Epoch: 20, Train Loss: 0.5582,  Val Loss: 0.6068
Epoch: 30, Train Loss: 0.5366,  Val Loss: 0.6078
Epoch: 40, Train Loss: 0.5207,  Val Loss: 0.5800
Epoch: 50, Train Loss: 0.5180,  Val Loss: 0.5702
Epoch: 60, Train Loss: 0.5060,  Val Loss: 0.5649
Epoch: 70, Train Loss: 0.5074,  Val Loss: 0.5341
Epoch: 80, Train Loss: 0.5044,  Val Loss: 0.6216
Epoch: 90, Train Loss: 0.5095,  Val Loss: 0.5318
Epoch: 100, Train Loss: 0.5057,  Val Loss: 0.5637
Epoch: 110, Train Loss: 0.5040,  Val Loss: 0.5425
Epoch: 120, Train Loss: 0.5020,  Val Loss: 0.5305
Epoch: 130, Train Loss: 0.4957,  Val Loss: 0.5568
Epoch: 140, Train Loss: 0.4956,  Val Loss: 0.5614


In [29]:
#getting the Loss for Test Data

with torch.no_grad():
    y_pred = aug_model(X_test)
    test_loss = loss_fn_aug(y_pred, Y_test)

print(f'Test loss: {test_loss.item()}')

Test loss: 0.4669162333011627


In [30]:
#getting the accuracy of the model

y_pred=aug_model(X_test)
accuracy = (y_pred.round() == Y_test).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.7857142686843872


In [31]:
#Printing the model output for data 10 data

predictions = (aug_model(X_test) > 0.5).int()
for i in range(10):
    print(f'{y_pred[i].item()} => {predictions[i].item()} (expected {Y_test[i].item()})')

0.8943246006965637 => 1 (expected 1.0)
0.14000295102596283 => 0 (expected 0.0)
0.1269301027059555 => 0 (expected 0.0)
0.6056459546089172 => 1 (expected 1.0)
0.1766650676727295 => 0 (expected 0.0)
0.032149676233530045 => 0 (expected 0.0)
0.6392236948013306 => 1 (expected 1.0)
0.7189096212387085 => 1 (expected 1.0)
0.3792495131492615 => 0 (expected 0.0)
0.5235176682472229 => 1 (expected 0.0)
